name: cal_new
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    flutter_lints: ^5.0.0
  characters: ^1.3.1
  collection: ^1.19.1
  material_color_utilities: ^0.12.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test_api: ^0.7.3

flutter:
  uses-material-design: true
